# Generated by Django 3.1.1 on 2021-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Circle is a official group')),
                ('is_public', models.BooleanField(default=False, help_text='Circle is checked as public')),
                ('is_limited', models.BooleanField(default=False, help_text='Check if a circle has limited number of members')),
                ('member_limited', models.PositiveIntegerField(default=0, help_text='Number of members')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_taken'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
